# Generated by Django 2.0.6 on 2018-10-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181025_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tip', models.CharField(blank=True, max_length=255, null=True)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.FieldType')),
            ],
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttypefield',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='products.ProductType'),
        ),
    ]
