# Generated by Django 2.0.6 on 2018-10-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181025_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeFieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='producttypefield',
            name='field_type',
        ),
        migrations.AddField(
            model_name='producttypefield',
            name='type',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Long Text'), (3, 'Number'), (4, 'Select'), (5, 'Check Box'), (6, 'Radio Button'), (7, 'File'), (8, 'Image')], default=1),
        ),
        migrations.DeleteModel(
            name='FieldType',
        ),
        migrations.AddField(
            model_name='producttypefield',
            name='choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductTypeFieldChoice'),
        ),
    ]
