# Generated by Django 2.0.6 on 2018-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181025_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttypefieldchoice',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
