# Generated by Django 2.1.2 on 2018-10-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181025_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttypefieldchoice',
            old_name='name',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='producttypefield',
            name='type',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Long Text'), (3, 'Number'), (4, 'Multi Value'), (5, 'File'), (6, 'Image')], default=1),
        ),
    ]
